# Generated by Django 5.2 on 2025-07-24 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customermerchandisestoreproductbuy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productBuyby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchandisestore',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchandisestorecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoryCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchandisestoreproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productCategory', to='store.merchandisestorecategory'),
        ),
        migrations.AddField(
            model_name='merchandisestoreproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchandisestoreproduct',
            name='is_love',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchandisestoreproduct',
            name='leagues_for',
            field=models.ManyToManyField(blank=True, to='team.leagues'),
        ),
        migrations.AddField(
            model_name='merchandiseproductspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificProduct', to='store.merchandisestoreproduct'),
        ),
        migrations.AddField(
            model_name='merchandiseproductimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImages', to='store.merchandisestoreproduct'),
        ),
        migrations.AddField(
            model_name='customermerchandisestoreproductbuy',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='store.merchandisestoreproduct'),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='product',
            field=models.ManyToManyField(blank=True, to='store.merchandisestoreproduct'),
        ),
        migrations.AddField(
            model_name='productdeliveryaddress',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customermerchandisestoreproductbuy',
            name='delivery_address_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productdeliveryaddress'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratedProduct', to='store.merchandisestoreproduct'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productRatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productsearchlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchLogs', to='store.merchandisestoreproduct'),
        ),
        migrations.AddField(
            model_name='productspecificationhighlights',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificHighlight', to='store.merchandiseproductspecification'),
        ),
        migrations.AddField(
            model_name='ratingimages',
            name='product_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingImages', to='store.productrating'),
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('user', 'product')},
        ),
    ]
