# Generated by Django 5.2 on 2025-07-24 09:01

import apps.team.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('leagues_start_date', models.DateTimeField(blank=True, null=True)),
                ('leagues_end_date', models.DateTimeField(blank=True, null=True)),
                ('registration_start_date', models.DateTimeField(blank=True, null=True)),
                ('registration_end_date', models.DateTimeField(blank=True, null=True)),
                ('registration_fee', models.IntegerField(default=5)),
                ('others_fees', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tournament_image/')),
                ('description', models.TextField(blank=True, null=True)),
                ('play_type', models.CharField(blank=True, choices=[('Group Stage', 'Group Stage'), ('Round Robin', 'Round Robin'), ('Single Elimination', 'Single Elimination'), ('Individual Match Play', 'Individual Match Play'), ('Round Robin Compete to Final', 'Round Robin Compete to Final'), ('Robin Randomizer', 'Robin Randomizer')], max_length=255, null=True)),
                ('max_number_team', models.PositiveIntegerField(default=2)),
                ('location', models.TextField(blank=True, help_text='location', null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=15, null=True)),
                ('longitude', models.CharField(blank=True, max_length=15, null=True)),
                ('complete_address', models.TextField(blank=True, help_text='street, city, state, country, PIN-postal_code', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('league_type', models.CharField(blank=True, choices=[('Invites only', 'Invites only'), ('Open to all', 'Open to all')], max_length=200, null=True)),
                ('invited_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_created', models.BooleanField(default=True)),
                ('any_rank', models.BooleanField(default=True)),
                ('start_rank', models.FloatField(blank=True, null=True)),
                ('end_rank', models.FloatField(blank=True, null=True)),
                ('policy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaguesCancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('within_day', models.IntegerField()),
                ('refund_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaguesPesrsonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaguesPlayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('Group Stage', 'Group Stage'), ('Round Robin', 'Round Robin'), ('Single Elimination', 'Single Elimination'), ('Individual Match Play', 'Individual Match Play'), ('Round Robin Compete to Final', 'Round Robin Compete to Final'), ('Robin Randomizer', 'Robin Randomizer')], max_length=255)),
                ('data', models.JSONField(default=apps.team.models.default_json)),
            ],
        ),
        migrations.CreateModel(
            name='LeaguesTeamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenPlayInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetailsForRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_for', models.CharField(max_length=255)),
                ('teams_ids', models.JSONField(blank=True, null=True)),
                ('charge_amount', models.FloatField(null=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('var_team_name', models.CharField(blank=True, max_length=250, null=True)),
                ('var_team_person', models.CharField(blank=True, max_length=250, null=True)),
                ('player_image', models.ImageField(blank=True, null=True, upload_to='player_image/')),
                ('player_first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('player_last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('player_full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('player_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('player_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('player_ranking', models.CharField(blank=True, default='1', max_length=255, null=True)),
                ('player_rank_lock', models.BooleanField(default=False)),
                ('identify_player', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoundRobinGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(blank=True, max_length=255, null=True)),
                ('number_sets', models.IntegerField(blank=True, null=True)),
                ('all_games_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SaveLeagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('team_person', models.CharField(blank=True, choices=[('Two Person Team', 'Two Person Team'), ('One Person Team', 'One Person Team')], max_length=250, null=True)),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='team_image/')),
                ('team_type', models.CharField(blank=True, choices=[('Women', 'Women'), ('Men', 'Men'), ('Co-ed', 'Co-ed'), ('Open-team', 'Open-team')], max_length=250, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('match_number', models.IntegerField(null=True)),
                ('winner_team_score', models.CharField(blank=True, max_length=250, null=True)),
                ('loser_team_score', models.CharField(blank=True, max_length=250, null=True)),
                ('play_ground_name', models.CharField(blank=True, max_length=250, null=True)),
                ('playing_date_time', models.DateTimeField(blank=True, null=True)),
                ('match_type', models.CharField(blank=True, max_length=250, null=True)),
                ('elimination_round', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('court_sn', models.IntegerField(blank=True, null=True)),
                ('court_real', models.IntegerField(blank=True, null=True)),
                ('is_drow', models.BooleanField(default=False)),
                ('set_number', models.IntegerField(blank=True, null=True)),
                ('court_num', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentScoreApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_approval', models.BooleanField(default=False)),
                ('team2_approval', models.BooleanField(default=False)),
                ('organizer_approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentScoreReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSetsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('set_number', models.IntegerField()),
                ('team1_point', models.IntegerField()),
                ('team2_point', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
