# Generated by Django 5.2 on 2025-07-24 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='add_organizer',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leagues',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_createdUserBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leagues',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_updatedUserBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaguescancellationpolicy',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.leagues'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='team_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_pesrson_type', to='team.leaguespesrsontype'),
        ),
        migrations.AddField(
            model_name='leaguesplaytype',
            name='league_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.leagues'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='team_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_team_type', to='team.leaguesteamtype'),
        ),
        migrations.AddField(
            model_name='openplayinvitation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_play_event', to='team.leagues'),
        ),
        migrations.AddField(
            model_name='openplayinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openplayinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_play_invitation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdetailsforregister',
            name='payment_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdetailsforregister',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='team.leagues'),
        ),
        migrations.AddField(
            model_name='player',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='follower_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerUpdatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roundrobingroup',
            name='league_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_for', to='team.leagues'),
        ),
        migrations.AddField(
            model_name='saveleagues',
            name='ch_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ch_league', to='team.leagues'),
        ),
        migrations.AddField(
            model_name='saveleagues',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='save_turnamenet_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamUpdatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saveleagues',
            name='ch_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ch_team', to='team.team'),
        ),
        migrations.AddField(
            model_name='roundrobingroup',
            name='all_teams',
            field=models.ManyToManyField(to='team.team'),
        ),
        migrations.AddField(
            model_name='roundrobingroup',
            name='seleced_teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seleced_teams', to='team.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(blank=True, to='team.team'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='registered_team',
            field=models.ManyToManyField(blank=True, to='team.team'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_team_for_all_league', to='team.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='team.roundrobingroup'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='leagues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues', to='team.leagues'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='loser_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_team', to='team.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='team.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='team.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_team', to='team.team'),
        ),
        migrations.AddField(
            model_name='tournamentscoreapproval',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_match', to='team.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentscorereport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentscorereport',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_match', to='team.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentsetsresult',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament', to='team.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentsetsresult',
            name='win_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_team', to='team.team'),
        ),
    ]
