# Generated by Django 5.2 on 2025-07-24 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisement_image/')),
                ('script_text', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_website', models.TextField(blank=True, null=True)),
                ('approved_by_admin', models.BooleanField(default=True)),
                ('admin_approve_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementDurationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('duration_type', models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Year', 'Year')], default='Days', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiserFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('facility_name', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_type', models.CharField(blank=True, choices=[('Pickleball Facility', 'Pickleball Facility'), ('Sports Facility', 'Sports Facility'), ('Country Club', 'Country Club'), ('Neighborhood Courts', 'Neighborhood Courts'), ('Public Area', 'Public Area'), ('Other', 'Other')], max_length=200, null=True)),
                ('court_type', models.CharField(blank=True, choices=[('Outdoor Court Only', 'Outdoor Court Only'), ('Indoor Court Only', 'Indoor Court Only'), ('Both Outdoor and Indoor', 'Both Outdoor and Indoor')], max_length=200, null=True)),
                ('membership_type', models.CharField(blank=True, choices=[('Open to Public', 'Open to Public'), ('Members only', 'Members only'), ('Pay to Play', 'Pay to Play')], max_length=200, null=True)),
                ('complete_address', models.TextField(blank=True, help_text='street, city, state, country, PIN-postal_code', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('number_of_courts', models.PositiveIntegerField()),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledgement', models.BooleanField(default=False)),
                ('is_view', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AmbassadorsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AmbassadorsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('file', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('post_text', models.TextField(blank=True, null=True)),
                ('approved_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_comment', models.IntegerField(default=0)),
                ('number_like', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('charge_for', models.CharField(blank=True, choices=[('Organizer', 'To Become an Organizer'), ('Sponsors', 'To Become a Sponsors'), ('Ambassador', 'To Become a Ambassador')], max_length=250, null=True, unique=True)),
                ('charge_amount', models.PositiveIntegerField(blank=True, help_text='subscription amount ($)', null=True)),
                ('effective_time', models.DurationField(blank=True, help_text='subscription duration of month number,i.e. [days hours:minutes:seconds], for 1 month [30 00:00:00]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Facility_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('screen', models.CharField(blank=True, choices=[('Player List', 'Player List'), ('User Team List', 'User Team List'), ('Leauge List', 'Leauge List'), ('Home', 'Home'), ('stats', 'Stats'), ('sponsor_view', 'Sponsor View'), ('sponsor_add', 'Sponsor Add')], max_length=250, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('var_chargeamount', models.FloatField(blank=True, null=True)),
                ('payment_for', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_for_id', models.TextField(blank=True, null=True)),
                ('payment_by', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_amount', models.FloatField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_response', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number_of_use', models.IntegerField(default=0)),
            ],
        ),
    ]
